Have the pre-commit hook also fix end-of-file nl

diff --git a/dev/tools/pre-commit b/dev/tools/pre-commit
--- a/dev/tools/pre-commit
+++ b/dev/tools/pre-commit
@@ -4,6 +4,24 @@
 
 set -e
 
+CODE=0
+for f in $(git diff --cached --name-only)
+do
+    if [ -e "$f" ] && dev/tools/should-check-whitespace.sh "$f"
+    then
+        dev/tools/check-eof-newline.sh "$f" || CODE=1
+        dev/tools/fix-eof-newline.sh "$f"
+    fi
+done
+
+if [ $CODE -ne 0 ]
+then
+    2>&1 echo "Some files had newline errors; they have been fixed in the working tree."
+    2>&1 echo "Make sure to add them before committing."
+    2>&1 echo "This may fix itself if you were using git commit -a, and you try again."
+    exit 1
+fi
+
 if git diff-index --check --cached HEAD >/dev/null 2>&1 ;
 then
     :
